spring.application.name=re-point
# ?? ??
server.port=8080

# ?????? ??
spring.application.name=repoint-backend

# Firestore ?? ?? (?? ? true? ??)
repoint.firestore.enabled=true

repoint.firestore.project-id=repoint-idiot
spring.cloud.gcp.firestore.enabled=true