
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6BegEpzM_1IdRps3tTFvkBCghJEwWGxQ',
    appId: '1:132968321662:android:11a02107897492df47fe2f',
    messagingSenderId: '132968321662',
    projectId: 'repoint-idiot',
    storageBucket: 'repoint-idiot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ov1ykCpZgV_zoIOoGaBmnpPlbDZlJ6k',
    appId: '1:132968321662:ios:1a4dcfcf6ec3079747fe2f',
    messagingSenderId: '132968321662',
    projectId: 'repoint-idiot',
    storageBucket: 'repoint-idiot.firebasestorage.app',
    androidClientId: '132968321662-89s1pm7v2hk8n1ii6kdcac1dnb8b1a1f.apps.googleusercontent.com',
    iosClientId: '132968321662-ddc8n0j7fgfd948seeuoj2frvquefn2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.repoint',
  );

}

